# Generated by Django 5.1.2 on 2024-10-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_key', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('states', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('send_message', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('information', models.TextField()),
                ('speaker', models.CharField(max_length=255)),
                ('ppt_link', models.URLField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='schedule_pics/')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GD',
            fields=[
                ('gd_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTeam',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='YebOffer',
            fields=[
                ('yeb_key', models.AutoField(primary_key=True, serialize=False)),
                ('short_desc', models.CharField(max_length=255)),
                ('large_desc', models.TextField()),
                ('campus', models.CharField(max_length=255)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('application_fee', models.IntegerField()),
                ('register_fee', models.IntegerField()),
                ('application_deadline', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yebapp.user')),
                ('r_no', models.CharField(max_length=10)),
                ('yeb_event', models.CharField(max_length=255)),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('u_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yebapp.user')),
                ('ach1', models.CharField(max_length=255)),
                ('ach2', models.CharField(max_length=255)),
                ('ach3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementPDF',
            fields=[
                ('u_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yebapp.user')),
                ('pdf_file', models.FileField(upload_to='achievement_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='StartupQuestion',
            fields=[
                ('u_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yebapp.user')),
                ('startup_name', models.CharField(max_length=255)),
                ('challenges', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('u_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yebapp.user')),
                ('p_name', models.CharField(max_length=255)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_phone', models.CharField(max_length=15)),
                ('school', models.CharField(max_length=255)),
                ('s_address', models.CharField(max_length=255)),
                ('s_city', models.CharField(max_length=100)),
                ('s_state', models.CharField(max_length=100)),
                ('marks', models.JSONField()),
                ('shirt_size', models.CharField(max_length=10)),
                ('shirt_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yebapp.schedule')),
                ('feedback_msg', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('expire_on', models.DateField()),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.participantteam')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='StdGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.JSONField()),
                ('gd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.gd')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('link', models.URLField()),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.assignment')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('yeb_event', models.CharField(max_length=255)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('pickup', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('staff', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='YebApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('u_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.user')),
                ('yeb_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.yeboffer')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='yeb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.yeboffer'),
        ),
        migrations.AddField(
            model_name='participantteam',
            name='yeb_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.yeboffer'),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('yeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.yeboffer')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='yeb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.yeboffer'),
        ),
        migrations.CreateModel(
            name='UTravel',
            fields=[
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yebapp.user')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yebapp.travel')),
            ],
        ),
    ]
