# Generated by Django 5.1.2 on 2024-10-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yebapp', '0002_alter_feedback_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='shirt_color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='shirt_size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=10),
        ),
    ]
